### ISSUE TITLE
Manifold from DirectSum.jl

### ISSUE THREAD

**Issue by chakravala** [JuliaManifolds/ManifoldsBase.jl#4]
Looks like you are copying some of my concepts from [DirectSum.jl](https://github.com/chakravala/DirectSum.jl), e.g. the `Manifold` type

Have you considered having a unified type system?

**Comment by mateuszbaran** [comment]
Hi!

I've looked at the description of your package, it looks quite impressive. Do you have a more standard interface (without unicode symbols or string literals) for `DirectSum.jl` and `Grassmann.jl`? It would certainly be useful for interoperability. Anyway, `Manifold.jl` and `ManifoldsBase.jl` are currently designed to bridge `Manopt.jl`, `FunManifolds.jl` and `Optim.jl` (and potentially some future manifold optimization packages). We will also likely have some manifold-based statistics in the future.

What kind of unified type system do you have in mind? I don't know how would you like to use `ManifoldsBase.jl` in your packages. I haven't really looked at your code (it's GPL and we have MIT license here).

**Comment by chakravala** [comment]
Well, I am not a user of those packages at the moment, but I am interested in the general interoperability of a `Manifold` type system.

> Do you have a more standard interface (without unicode symbols or string literals)

Yes, you can indeed do printing of indices with OR without unicode characters (only ASCII). However, this feature is not in its final form yet.

**Comment by mateuszbaran** [comment]
It would definitely be great to have a common part of the interface. What operations do you think we could share? Looking at readmes of your packages, their interfaces look very different from what we have here. Anyway, if you have any specific requirements for a common interface you can just write about it here and we can discuss how `ManifoldsBase.jl` could be modified to accommodate them.

> Yes, you can indeed do printing of indices with OR without unicode characters (only ASCII). However, this feature is not in its final form yet.

Nice, I'd like to see some examples once they are ready.

**Comment by sethaxen** [comment]
As @mateuszbaran pointed out, `Manifolds.jl` grew out of a desire to unify the type systems of several packages. See https://discourse.julialang.org/t/ann-manopt-jl and https://discourse.julialang.org/t/towards-a-common-manifold-framework-package for initial discussions. The packages it unifies have a definite optimization flavor, hence `Manifolds.jl` shares that focus and is hosted in JuliaNLSolvers.

However, we're also interested it in providing general interfaces and functionality for working with manifolds across the Julia ecosystem. My interest in particular is doing statistics on manifolds. So if we can find a way to provide the features you need in `Manifolds.jl`, we would very much be open to that.

**Comment by chakravala** [comment]
The way I see it, it seems that your infrastructure is based on the traditional matrix algebra approach to the interoperability of the manifolds in general. However, in my [Grassmann.jl](https://github.com/chakravala/Grassmann.jl) package I am not using the matrix algebra approach to manifolds... instead I am using a differential geometric algebra / multivector simplicial complex construction for manifolds.

Therefore, there is a fundamental difference in design and problem approach used. However, the reason for making the [DirectSum.jl](https://github.com/chakravala/DirectSum.jl) and [AbstractTensors.jl](https://github.com/chakravala/AbstractTensors.jl) separate abstractions is to help enable interoperability across the wider Julia package ecosystem with manifolds.

Currently, the `DirectSum` package is only designed to meet my own requirements and needs for the approach to manifolds based on `Grassmann` algebra. For this, I have created an abstract type which is called `Manifold{N}` where `N` is the dimension of the manifold. This abstract type contains several subtypes of `VectorBundle` and `SubManifold` variations. The `VectorBundle` types specify various properties for a specific `Manifold` space, such as the metric tensor and projection indices. Alternatively, the `SubManifold` contains a `VectorBundle` in its type parameters with an additional parameter that specifies a submanifold index encoding. Various operations and methods are available to manipulate these `Manifold` spaces, such as `ndims` or `+` for direct sums of spaces, as well as unions and intersections and various other properties and features (e.g. index printing methods).

> Nice, I'd like to see some examples once they are ready.

It is already possible to get ASCII `Symbol` like this, but it may still get re-designed.
```Julia
julia> DirectSum.indexsymbol(ℝ^62,UInt(2^62-1))
:x12345678910ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
```

By having a common `DirectSum` type interoperability for `Manifold{N}` abstract types, I was hoping that the interoperability between the matrix algebra approach and the `Grassmann` algebra approach should be more easily attainable. If the goal is to have a unified interoperability for the two different approaches to `Manifold` (matrix algebra vs geometric algebra), then it would make sense to have a unified `DirectSum` interoperability at the root of it. This is why I made `DirectSum` separate.

**Comment by kellertuer** [comment]
Our manifold points can actually be based on any type and are not necessarily bound to the matrix algebra. For example _how_ you represent a point on a manifold is completely your own choice, even whether you want to be a subtype of `MPoint` or not (in our case for now this case is "just" used for arrays, i.e. the matrix algebra approach, yes) but that does not limit this idea to matrix algebra approaches. the types are more general, as long as you for example provide _some_ implementation of functions you need, e.g. the exponential and the logarithmic map.

And I also would refrain from "copying" something from you, since the manifold type if something that general that one easily comes up with something like that completely independent (for example Manopt.jl does that since mid 2017, Mateus surely also has had early ideas on that in FunManifold).

That aside, I think if we find a way to provide a unified way for your approach and ours, I'd happily welcome that. Be it for `DirectSum` or for manifold representations in general, as @mateuszbaran already said.

**Comment by mateuszbaran** [comment]
I think that there might be a small confusion about having a type interoperability between packages. In Julia extending certain abstract types is a secondary issue to what _operations_ we want to share. These abstract types are there just to push polymorphic dispatch into right methods. That's why we have the `Manifold` abstract type but we don't require points to implement a specific abstract type. And the interface is not totally about traditional matrix algebra approach, I have a work-in-progress implementation of the manifold of curves on a manifold that allows many operations without a specific discretization.

So, what functions should we share? At the moment we focus on operations on points or elements of some vector bundles (mostly the tangent and cotangent bundle at the moment), while you write about operations on manifolds and vector bundles themselves. It would certainly be nice to be able to have direct sums or submanifolds in our ecosystem but we have a limited capacity and have to prioritize some issues over other. I still have quite a bit of work to change `FunManifolds.jl` and my unpublished code to the interface we have here.

We already have an implementation of vector bundles in `Manifolds.jl` that would certainly benefit from interoperability with `DirectSum.jl`. I'm still struggling with things like different types of manifold derivatives, exterior products, etc. -- especially with how to represent points and vectors. What would a function calculating an exterior product of two vectors return? That is supposed to work for any tangent vectors to any manifold represented in any valid way as long as our interface is implemented. I don't know how to do that.

**Comment by chakravala** [comment]
These things like elements of vector bundles are already handled in `Grassmann.jl` quite well. In the algebra of `Grassmann` there are operations on points and higher grade `TensorAlgebra{V}` elements. All of the `TensorAlgebra{V}` elements contain a vector bundle `Manifold` in their type parameters. This `Manifold` in each element's type specifies interoperability, so that an element can be converted. This is why you need `DirectSum` for interoperability, because all `TensorAlgebra` elements of the exterior and differential algebras require a `Manifold` space.

It is possible to setup a correspondence between matrix group elements and `Grassmann` elements. However, I don't currently use the matrix approach, so this is not so important to me yet. I just only wanted to see what kind of interoperability might be possible in the future.

If you want to use `DirectSum` as a starting point for some kind of interoperability, let me know.

**Comment by mateuszbaran** [comment]
Thanks, it would help if you had an example of converting tangent vectors from an array representation to your representation, doing some operations and converting the result back to an array representation. Currently I don't have any applications for that so I won't spend much time on this in the near future.

**Comment by kellertuer** [comment]
Since this is inactive for over a year, let's close this for now. If we have any steps towards a common interface, we can surely reopen this one.
